from __future__ import annotations

from pathlib import Path
from typing import Protocol


class AssetRepository(Protocol):
    def ensure_dir(self, path: Path) -> None: ...
    def is_file(self, path: Path) -> bool: ...
    def copy_file(self, src: Path, dest: Path) -> None: ...
    def list_assets(self, directory: Path, kind: str) -> list[Path]: ...
    def remove_file(self, path: Path) -> None: ...
    def file_exists(self, path: Path) -> bool: ...
