from __future__ import annotations

from typing import Protocol

from docs.domain.runtime_records import Blob


class BlobStore(Protocol):
    def put(self, blob: Blob, content: bytes) -> None: ...
    def put_conditional(self, blob: Blob, content: bytes, *, expected_digest: str | None) -> bool: ...
    def compare_and_swap(self, key: str, expected_digest: str | None, blob: Blob, content: bytes) -> bool: ...
    def get(self, key: str) -> tuple[Blob, bytes] | None: ...
