from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class EvidenceRepository(Protocol):
    def hash_file(self, path: Path) -> str: ...
    def hash_json(self, value: Any) -> str: ...
    def list_manual_files(self, manual_dir: Path) -> list[Path]: ...
    def read_text(self, path: Path) -> str: ...
    def file_exists(self, path: Path) -> bool: ...
    def file_size(self, path: Path) -> int: ...
    def list_traceability_files(self, extracted_dir: Path) -> list[Path]: ...
    def read_manifest(self, path: Path) -> dict[str, Any] | None: ...
    def write_manifest(self, path: Path, payload: dict[str, Any]) -> None: ...
