from __future__ import annotations

import builtins as _builtins
from typing import Protocol

from docs.domain.runtime_records import Artifact, Passport, Run


class RunStore(Protocol):
    def put(self, run: Run) -> None: ...
    def get(self, run_id: str) -> Run | None: ...
    def list(self) -> _builtins.list[Run]: ...


class PassportStore(Protocol):
    def put(self, passport: Passport) -> None: ...
    def get(self, run_id: str) -> Passport | None: ...


class ArtifactStore(Protocol):
    def put(self, artifact: Artifact) -> None: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def list(self) -> _builtins.list[Artifact]: ...
    def list_for_run(self, run_id: str) -> _builtins.list[Artifact]: ...
