from __future__ import annotations

from pathlib import Path
from typing import Protocol


class SectionRepository(Protocol):
    def section_path(self, doc_id: str, order: int, section_id: str) -> Path: ...
    def sections_dir_exists(self, doc_id: str) -> bool: ...
    def section_exists(self, doc_id: str, order: int, section_id: str) -> bool: ...
    def read_section(self, doc_id: str, order: int, section_id: str) -> tuple[dict, str]: ...
