from __future__ import annotations

from pathlib import Path
from typing import Protocol


class SectionRepository(Protocol):
    def section_path(self, doc_id: str, order: int, section_id: str) -> Path: ...
    def sections_dir_exists(self, doc_id: str) -> bool: ...
    def section_exists(self, doc_id: str, order: int, section_id: str) -> bool: ...
    def read_section(self, doc_id: str, order: int, section_id: str) -> tuple[dict, str]: ...
    def write_section(self, doc_id: str, order: int, section_id: str, raw_text: str) -> None: ...
    def write_proposal_section(self, doc_id: str, order: int, section_id: str, raw_text: str) -> Path: ...
    def context_pack_path(self, doc_id: str, order: int, section_id: str) -> Path: ...
    def document_context_pack_path(self, doc_id: str) -> Path: ...
    def write_context_pack(self, path: Path, content: str) -> Path: ...
    def find_section_file(self, doc_id: str, section_id: str) -> Path | None: ...
    def read_raw_text(self, path: Path) -> str: ...
    def write_raw_text(self, path: Path, content: str) -> None: ...
