from __future__ import annotations

from pathlib import Path
from typing import Protocol


class SourceRepository(Protocol):
    def glob_markdown(self, directory: Path) -> list[Path]: ...
    def read_context_texts(self, context_dir: Path) -> dict[str, str]: ...
    def glob_pattern(self, root: Path, pattern: str) -> list[Path]: ...
    def find_executable(self, name: str) -> str | None: ...
    def run_gh_issue_list(self, gh_path: str, repo: str) -> str: ...
    def run_git_log(self, path: Path, repo_root: Path) -> str | None: ...
    def detect_github_remote(self, repo_root: Path) -> str: ...
    def run_git_rev_parse_head(self, repo_root: Path) -> str: ...
