from __future__ import annotations

from typing import Protocol

from docs.domain.contracts import Artifact, Blob, Graph, Job, Passport, Run


class RunStore(Protocol):
    def put(self, run: Run) -> None: ...
    def get(self, run_id: str) -> Run | None: ...


class PassportStore(Protocol):
    def put(self, passport: Passport) -> None: ...
    def get(self, run_id: str) -> Passport | None: ...


class ArtifactStore(Protocol):
    def put(self, artifact: Artifact) -> None: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def list_for_run(self, run_id: str) -> list[Artifact]: ...


class BlobStore(Protocol):
    def put(self, blob: Blob, content: bytes) -> None: ...
    def get(self, key: str) -> tuple[Blob, bytes] | None: ...


class GraphStore(Protocol):
    def put(self, graph: Graph) -> None: ...
    def get(self) -> Graph: ...


class JobQueue(Protocol):
    def enqueue(self, job_id: str, payload: dict[str, object]) -> None: ...
    def claim(self, worker_id: str) -> Job | None: ...
    def ack(self, job_id: str, worker_id: str) -> bool: ...


class LeaseStore(Protocol):
    def acquire(self, resource: str, owner: str, ttl_seconds: int) -> bool: ...
    def renew(self, resource: str, owner: str, ttl_seconds: int) -> bool: ...
    def release(self, resource: str, owner: str) -> bool: ...
