import React,{useEffect,useState} from "react";
import {mockApi} from "./api/mockApi"; import type {Status} from "./api/models"; import {StatusBadge} from "./components/StatusBadge"; import "./styles.css";
import {ReviewApiClient} from "./api/client";
const nav=[["overview","Workspace"],["runs","Run history"],["findings","Findings inbox"],["artifacts","Artifact preview"],["passport","Evidence passport"],["graph","Semantic graph"],["templates","Templates"],["baselines","Baselines"],["revisions","Revisions"],["publication","Publication status"]] as const;
function useRoute(){const get=()=>location.hash.slice(1)||"overview";const [route,setRoute]=useState(get);useEffect(()=>{const f=()=>setRoute(get());addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);return route}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={"card "+className}>{children}</section>}
function PageHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="page-head"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p></div>}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Overview({go}:{go:(r:string)=>void}){return <><PageHead eyebrow="ACTIVE WORKSPACE" title="Safety case — northstar" copy="Review workspace for deterministic document QA, evidence traceability, and publication readiness."/><div className="metric-grid">{[["Latest run","Warnings","run-2026-09-15-1432"],["Findings","7 open","3 blockers"],["Evidence coverage","92%","3 unresolved claims"],["Publication","Staging","Awaiting approval"]].map(([a,b,c])=><button className="metric card" key={a} onClick={()=>go(a==="Findings"?"findings":a==="Latest run"?"runs":a==="Evidence coverage"?"passport":"publication")}><span>{a}</span><strong>{b}</strong><small>{c}</small></button>)}</div><div className="two-col"><Card><div className="card-title"><h2>Review readiness</h2><StatusBadge status="warnings"/></div><div className="progress"><span style={{width:"76%"}}/></div><p className="muted">76% of the release checklist is complete.</p><button className="button" onClick={()=>go("findings")}>Open findings inbox</button></Card><Card><div className="card-title"><h2>Recent activity</h2><a href="#runs">View all</a></div><ul className="activity"><li><b>Run completed</b><span>7 findings · 12 artifacts · 12 min ago</span></li><li><b>Baseline updated</b><span>Northstar release candidate · 1 hr ago</span></li><li><b>Passport attested</b><span>48 attestations · Yesterday</span></li></ul></Card></div></>}
const listRuns = () => remoteOrMock(remoteClient ? () => remoteClient.listRuns() : null, mockApi.listRuns);
const listFindings = () => remoteOrMock(remoteClient ? () => remoteClient.listFindings() : null, mockApi.listFindings);
const listArtifacts = () => remoteOrMock(remoteClient ? () => remoteClient.listArtifacts() : null, mockApi.listArtifacts);
function Runs(){const [data,setData]=useState<any[]>([]);const [error,setError]=useState("");const [progress,setProgress]=useState<any>();useEffect(()=>{listRuns().then(setData).catch(()=>setError("Unable to load runs; showing no results."))},[]);useEffect(()=>{if(!remoteClient)return;const controller=new AbortController();remoteClient.streamProgress("run-2026-09-15-1432",setProgress,controller.signal).catch(()=>undefined);return()=>controller.abort()},[]);return <><PageHead eyebrow="EXECUTION" title="Run history" copy="Deterministic checks across the active document and its derived artifacts."/>{error&&<p className="callout" role="status">{error}</p>}{progress&&<p className="callout" role="status" aria-live="polite">Live progress: {progress.message??progress.type}{progress.progress!==undefined?` (${progress.progress}%)`:""}</p>}<Card><Table headers={["Run","Started","Duration","Findings","Artifacts","Status"]} rows={data.map(r=>[<button className="link-button">{r.id}</button>,r.startedAt,r.duration,r.findings,r.artifactCount,<StatusBadge status={r.status}/>])}/></Card></>}
function Findings(){const [q,setQ]=useState("");const [data,setData]=useState<any[]>([]);const [error,setError]=useState("");useEffect(()=>{listFindings().then(setData).catch(()=>setError("Unable to load findings; showing no results."))},[]);const filtered=data.filter(f=>(f.title+f.location+f.status).toLowerCase().includes(q.toLowerCase()));return <><PageHead eyebrow="TRIAGE" title="Findings inbox" copy="Prioritize the evidence and presentation issues that affect release confidence."/>{error&&<p className="callout" role="status">{error}</p>}<Card><div className="toolbar"><label htmlFor="filter">Filter findings</label><input id="filter" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, location, status" /></div><div className="finding-list">{filtered.map(f=><article className="finding" key={f.id}><div className="finding-top"><span className="kicker">{f.id} · {f.severity}</span><StatusBadge status={f.status}/></div><h2>{f.title}</h2><p>{f.summary}</p><div className="finding-meta"><span>{f.location}</span><span>Owner: {f.owner}</span><span>{f.updated}</span></div></article>)}</div>{!filtered.length&&<p className="empty">No findings match. Try a broader search term.</p>}</Card></>}
function Artifacts(){const [data,setData]=useState<any[]>([]);const [error,setError]=useState("");useEffect(()=>{listArtifacts().then(setData).catch(()=>setError("Unable to load artifacts; showing no results."))},[]);return <><PageHead eyebrow="OUTPUTS" title="Artifact & page preview" copy="Inspect generated outputs and the visual evidence attached to each one."/>{error&&<p className="callout" role="status">{error}</p>}<div className="artifact-grid">{data.map(a=><Card key={a.id}><div className="artifact-preview"><span>{a.kind}</span><b>{a.kind==="PNG"?"Page 11 preview":"Document artifact"}</b></div><div className="card-title"><h2>{a.name}</h2><StatusBadge status={a.status}/></div><p className="muted">{a.size}{a.pages?" · "+a.pages+" pages":""} · {a.checksum}</p><button className="button secondary">Inspect artifact</button></Card>)}</div></>}
function Passport(){const [p,setP]=useState<any>();const [error,setError]=useState("");useEffect(()=>{(remoteClient?remoteClient.getPassport("run-2026-09-15-1432"):mockApi.getPassport("run-2026-09-15-1432")).then(setP).catch(()=>setError("Unable to load the evidence passport."))},[]);return <><PageHead eyebrow="PROVENANCE" title="Evidence passport" copy="A content-bound attestation of claims, sources, and the run that produced them."/>{error&&<p className="callout" role="status">{error}</p>}<Card>{p&&<><div className="card-title"><h2>Passport {p.id}</h2><StatusBadge status="warnings"/></div><p className="muted">Verified {p.verifiedAt} · Run {p.runId}</p><div className="metric-grid compact">{[[p.coverage+"%","Coverage"],[p.attestations,"Attestations"],[p.sources,"Sources"],[p.claims,"Claims"],[p.unresolved,"Unresolved"]].map(([v,l])=><div className="mini-metric" key={String(l)}><strong>{v}</strong><span>{l}</span></div>)}</div><div className="callout"><b>3 claims need attention.</b> Every other claim has a source locator and stable content hash.</div></>}</Card></>}
type GraphQueryOption = { query:import("./api/models").GraphQuery; label:string; needsId?:boolean; idLabel?:string };
const graphQueries:GraphQueryOption[] = [
  {query:"claims_without_evidence",label:"Claims without evidence"},
  {query:"findings_affected_by_revision",label:"Findings affected by revision",needsId:true,idLabel:"Revision id"},
  {query:"artifacts_derived_from_input",label:"Artifacts derived from input",needsId:true,idLabel:"Input id"},
  {query:"unused_references",label:"Unused references"},
  {query:"unmet_requirements",label:"Unmet requirements"}
];
function stableJson(value:unknown):string { if(value===null||typeof value!=="object") return JSON.stringify(value); if(Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; const record=value as Record<string,unknown>; return `{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${stableJson(record[key])}`).join(",")}}`; }
function queryItemValue(value:unknown):string { return typeof value === "string" ? value : stableJson(value); }
function Graph(){
  const [g,setG]=useState<{nodes:import("./api/models").GraphNode[];edges:import("./api/models").GraphEdge[]}|undefined>(); const [error,setError]=useState(""); const [selectedQuery,setSelectedQuery]=useState<import("./api/models").GraphQuery>("claims_without_evidence"); const [queryId,setQueryId]=useState(""); const [queryResult,setQueryResult]=useState<import("./api/models").GraphQueryResult>(); const [queryLoading,setQueryLoading]=useState(false); const [queryError,setQueryError]=useState("");
  useEffect(()=>{(remoteClient?remoteClient.getGraph():mockApi.getGraph()).then(setG).catch(()=>setError("Unable to load the semantic graph."))},[]);
  const option=graphQueries.find(item=>item.query===selectedQuery)??graphQueries[0];
  const runQuery=()=>{ if(option.needsId&&!queryId.trim()){setQueryError(`${option.idLabel} is required for this query.`);setQueryResult(undefined);return;} setQueryLoading(true);setQueryError("");setQueryResult(undefined); const request=remoteClient?remoteClient.getGraphQuery(selectedQuery,queryId.trim()||undefined):mockApi.getGraphQuery(selectedQuery,queryId.trim()||undefined); request.then(setQueryResult).catch(()=>setQueryError("Unable to load this graph query. The full graph and passport remain available for context.")).finally(()=>setQueryLoading(false)); };
  const queryRows=queryResult?.items.map(item=>[item.id,item.kind,item.label,item.confidence===undefined?"—":`${Math.round(item.confidence*100)}%`,queryItemValue(item.attributes??{})]);
  return <><PageHead eyebrow="TRACEABILITY" title="Semantic graph" copy="Explore how claims connect to evidence, sections, and rendered artifacts."/>{error&&<p className="callout" role="status">{error}</p>}<Card><div className="graph"><svg viewBox="0 0 100 100" role="img" aria-label="Semantic graph connecting source, claim, section, and artifact">{g?.edges.map(e=>{const from=g.nodes.find(n=>n.id===e.from);const to=g.nodes.find(n=>n.id===e.to);return from&&to?<line key={e.from+e.to} x1={from.x} y1={from.y} x2={to.x} y2={to.y}/>:null})}{g?.nodes.map(n=><g key={n.id}><circle cx={n.x} cy={n.y} r="5"/><text x={n.x} y={n.y+11} textAnchor="middle">{n.label}</text></g>)}</svg></div><div className="legend">{g?.nodes.map(n=><span key={n.id}><i className={"dot "+n.type}/>{n.type} · {Math.round(n.confidence*100)}% confidence</span>)}</div><div className="callout" style={{marginTop:18}}><b>Context before conclusions.</b> Graph query results are exploratory views, not attestations. Interpret them with the full graph and the evidence passport before treating any item as review evidence.</div></Card><Card><div className="card-title"><h2>Domain explorer</h2><span className="muted">Read-only graph queries</span></div><div className="toolbar" style={{alignItems:"flex-end",flexWrap:"wrap"}}><div><label htmlFor="graph-query">Query</label><select id="graph-query" value={selectedQuery} onChange={event=>{setSelectedQuery(event.target.value as import("./api/models").GraphQuery);setQueryResult(undefined);setQueryError("")}} style={{display:"block",minHeight:42,padding:"8px 10px",border:"1px solid #cfd7e5",borderRadius:7}}>{graphQueries.map(item=><option key={item.query} value={item.query}>{item.label}</option>)}</select></div>{option.needsId&&<div><label htmlFor="graph-query-id">{option.idLabel}</label><input id="graph-query-id" value={queryId} onChange={event=>setQueryId(event.target.value)} placeholder="Enter identifier" /></div>}<button className="button" type="button" onClick={runQuery} disabled={queryLoading}>{queryLoading?"Loading…":"Run query"}</button></div>{queryError&&<p className="callout" role="alert">{queryError}</p>}{queryLoading&&<p className="muted" role="status" aria-live="polite">Loading query results…</p>}{!queryLoading&&queryResult&&<div role="status" aria-live="polite">{queryResult.graphUnavailable&&<p className="callout">The graph is unavailable; this result is empty and cannot support a conclusion.</p>}{queryResult.warnings?.map(warning=><p className="muted" key={warning}>{warning}</p>)}{queryResult.items.length===0?<p className="empty">No matching nodes were returned.</p>:<><div className="table-wrap"><Table headers={["ID","Kind","Label","Confidence","Attributes"]} rows={queryRows??[]}/></div><details style={{marginTop:18}}><summary>View deterministic JSON</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",fontSize:12}}>{stableJson(queryResult)}</pre></details></>}</div>}</Card></>;
}
const remoteClient = import.meta.env.VITE_DOCS_API_BASE_URL ? new ReviewApiClient({baseUrl: import.meta.env.VITE_DOCS_API_BASE_URL}) : null;
async function remoteOrMock<T>(remote: (()=>Promise<{items:T[]}>)|null, fallback: ()=>Promise<T[]>): Promise<T[]> {
  if (!remote) return fallback();
  try { return (await remote()).items; } catch { return fallback(); }
}
const listTemplates = () => remoteOrMock(remoteClient ? () => remoteClient.listTemplates() : null, mockApi.listTemplates);
const listBaselines = () => remoteOrMock(remoteClient ? () => remoteClient.listBaselines() : null, mockApi.listBaselines);
const listRevisions = () => remoteOrMock(remoteClient ? () => remoteClient.listRevisions() : null, mockApi.listRevisions);
const listPublications = () => remoteOrMock(null, mockApi.listPublications);
const renderTemplate = (x:any): React.ReactNode[] => [<b>{x.name}</b>,x.version,x.sections,<StatusBadge status={x.contract}/>,x.updated];
const renderBaseline = (x:any): React.ReactNode[] => [<b>{x.name}</b>,x.scope,x.created,x.delta,<StatusBadge status={x.status}/>];
const renderRevision = (x:any): React.ReactNode[] => [x.message,x.author,x.date,x.files,<StatusBadge status={x.status}/>];
const renderPublication = (x:any): React.ReactNode[] => [<b>{x.environment}</b>,x.artifact,x.publishedAt,x.approver,<StatusBadge status={x.status}/>];
function DataView({kind,title,copy,api,headers,render}:{kind:string;title:string;copy:string;api:()=>Promise<any[]>;headers:string[];render:(x:any)=>React.ReactNode[]}){const [data,setData]=useState<any[]>([]);useEffect(()=>{api().then(setData)},[api]);return <><PageHead eyebrow={kind.toUpperCase()} title={title} copy={copy}/><Card><Table headers={headers} rows={data.map(render)}/></Card></>}
function App(){const route=useRoute();const go=(r:string)=>{location.hash=r;document.getElementById("main")?.focus()};let view:React.ReactNode;if(route==="overview")view=<Overview go={go}/>;else if(route==="runs")view=<Runs/>;else if(route==="findings")view=<Findings/>;else if(route==="artifacts")view=<Artifacts/>;else if(route==="passport")view=<Passport/>;else if(route==="graph")view=<Graph/>;else if(route==="templates")view=<DataView kind="configuration" title="Templates" copy="Contracts that define structure, evidence rules, and output expectations." api={listTemplates} headers={["Template","Version","Sections","Contract","Updated"]} render={renderTemplate}/>;else if(route==="baselines")view=<DataView kind="visual QA" title="Baselines" copy="Stable comparison points for rendered pages and release candidates." api={listBaselines} headers={["Baseline","Scope","Created","Delta","Status"]} render={renderBaseline}/>;else if(route==="revisions")view=<DataView kind="change log" title="Revisions" copy="Auditable edits and their review state across the active document." api={listRevisions} headers={["Revision","Author","Date","Files","Status"]} render={renderRevision}/>;else view=<DataView kind="release" title="Publication status" copy="Track verified artifacts as they move through staging and production." api={listPublications} headers={["Environment","Artifact","Published","Approver","Status"]} render={renderPublication}/>;return <div className="app"><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="#overview"><span className="brand-mark">R</span><span>Review <b>Studio</b></span></a><div className="header-meta"><span className="chip">● Local workspace</span><button className="icon-button" aria-label="Open command menu">⌘ K</button><button className="avatar" aria-label="Account menu">AR</button></div></header><div className="layout"><aside><div className="workspace-label">WORKSPACE</div><button className="workspace-switcher">Northstar safety case <span>⌄</span></button><nav aria-label="Review Studio"><ul>{nav.map(([id,label],i)=><li key={id}><a href={"#"+id} aria-current={route===id?"page":undefined}><span className="nav-icon" aria-hidden="true">{["◈","◷","!","▧","✓","⌘","◇","◌","↗","→"][i]}</span>{label}</a></li>)}</ul></nav><div className="sidebar-footer"><span className="avatar small">AR</span><span><b>Alex Rivera</b><small>Reviewer</small></span></div></aside><main id="main" tabIndex={-1}>{view}</main></div><footer><span>Review Studio foundation</span><span>API adapter: mock /v1 · Last sync 12 min ago</span></footer><div className="sr-only" aria-live="polite">{route} view loaded</div></div>}
export default App;
